spring.application.name=gestion_restaurant
spring.datasource.url=jdbc:mysql://localHost:3306/gestion_restaurant
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
 #server.port=8081
 spring.jpa.properties.hibernate.format_sql=true
 # JWT Configuration
jwt.secret=MaCleTresSecreteEtTresLonguePourGererMonRestaurant2026!
jwt.expiration=86400000
jwt.tokenPrefix=Bearer 
jwt.authHeader=Authorization
spring.jpa.open-in-view=false

# Security logging (optionnel)
logging.level.org.springframework.security=DEBUG

# Désactiver la création automatique d'utilisateur
spring.security.user.name=
spring.security.user.password=